# Generated by GitHub Copilot
FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY pyproject.toml README.md ./
COPY src ./src

RUN pip install --no-cache-dir -e .

EXPOSE 8003

CMD ["uvicorn", "hallucination_lens.api:app", "--host", "0.0.0.0", "--port", "8003"]
