# Generated by GitHub Copilot
"""Call the hallucination-lens API score endpoint from a local script."""

from __future__ import annotations

import json
from urllib import request


# Generated by GitHub Copilot
def main() -> None:
    """Send one POST /score request and print the parsed response."""

    payload = {
        "context": "Paris is the capital of France.",
        "response": "Paris is in France.",
        "threshold": 0.6,
    }

    req = request.Request(
        "http://127.0.0.1:8003/score",
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST",
    )

    with request.urlopen(req, timeout=30) as response:
        body = json.loads(response.read().decode("utf-8"))

    print(
        {
            "score": round(body["score"], 4),
            "verdict": body["verdict"],
            "threshold": body["threshold"],
            "request_id": body.get("request_id"),
        }
    )


if __name__ == "__main__":
    main()
