# Generated by GitHub Copilot
"""Run batch scoring from a local JSON benchmark input file."""

from __future__ import annotations

import json
from pathlib import Path

from hallucination_lens import HallucinationScorer


# Generated by GitHub Copilot
def load_pairs(path: Path) -> list[tuple[str, str]]:
    """Load context-response pairs from JSON file for batch scoring."""

    payload = json.loads(path.read_text(encoding="utf-8"))
    pairs: list[tuple[str, str]] = []
    for item in payload:
        pairs.append((str(item["context"]), str(item["response"])))
    return pairs


# Generated by GitHub Copilot
def main() -> None:
    """Run batch scoring and print summary metrics for the dataset."""

    dataset_path = Path("benchmarks/batch-input.json")
    pairs = load_pairs(dataset_path)

    scorer = HallucinationScorer(threshold=0.6)
    results = scorer.batch_faithfulness_scores(pairs)

    faithful = sum(1 for item in results if item.verdict == "faithful")
    hallucinated = sum(1 for item in results if item.verdict == "hallucinated")
    average_score = sum(item.score for item in results) / len(results)

    print(
        {
            "item_count": len(results),
            "average_score": round(average_score, 4),
            "faithful": faithful,
            "hallucinated": hallucinated,
        }
    )


if __name__ == "__main__":
    main()
