# Generated by GitHub Copilot
"""Run a single faithfulness score using the Python library interface."""

from hallucination_lens import HallucinationScorer


# Generated by GitHub Copilot
def main() -> None:
    """Run one scoring call and print a compact result payload."""

    scorer = HallucinationScorer(threshold=0.6)
    result = scorer.faithfulness_score(
        context="Paris is the capital of France.",
        response="Paris is in France.",
    )

    print(
        {
            "score": round(result.score, 4),
            "verdict": result.verdict,
            "threshold": result.threshold,
            "model_name": scorer.model_name,
        }
    )


if __name__ == "__main__":
    main()
