# Generated by GitHub Copilot
"""Command line interface for hallucination-lens."""

from __future__ import annotations

import argparse
import json
import sys
from typing import Sequence

from .scorer import HallucinationScorer
from .validators import validate_text_argument, validate_threshold


def build_parser() -> argparse.ArgumentParser:
    """Build and return the CLI argument parser."""

    parser = argparse.ArgumentParser(
        prog="hallucination-lens",
        description="Score how faithful an LLM response is to the provided context.",
    )
    parser.add_argument("--context", required=True, help="Source context text")
    parser.add_argument("--response", required=True, help="Model response text")
    parser.add_argument(
        "--threshold",
        type=float,
        default=0.6,
        help="Faithfulness threshold between 0 and 1 (default: 0.6)",
    )
    parser.add_argument(
        "--model-name",
        default="sentence-transformers/all-MiniLM-L6-v2",
        help="Sentence-transformers model identifier",
    )
    parser.add_argument(
        "--pretty",
        action="store_true",
        help="Pretty-print JSON output",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    """Run the CLI application and return a process exit code."""

    parser = build_parser()
    args = parser.parse_args(argv)

    try:
        context = validate_text_argument("context", args.context)
        response = validate_text_argument("response", args.response)
        threshold = validate_threshold(args.threshold)

        scorer = HallucinationScorer(model_name=args.model_name, threshold=threshold)
        result = scorer.faithfulness_score(context=context, response=response)

        payload = {
            "confidence": round(result.score, 6),
            "verdict": result.verdict,
            "threshold": result.threshold,
            "model_name": scorer.model_name,
            "sentence_scores": [
                {
                    "sentence": item.sentence,
                    "max_similarity": round(item.max_similarity, 6),
                }
                for item in result.sentence_scores
            ],
        }

        indent = 2 if args.pretty else None
        print(json.dumps(payload, indent=indent))
        return 0
    except Exception as exc:  # pragma: no cover - defensive top-level CLI boundary
        print(json.dumps({"error": str(exc)}), file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
